// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPD5Zma9lMNjonB__6BBTNOdc5O7Qf5zU',
    appId: '1:775834354005:web:64b2e52b44e969543e2fdc',
    messagingSenderId: '775834354005',
    projectId: 'my-day-962ec',
    authDomain: 'my-day-962ec.firebaseapp.com',
    storageBucket: 'my-day-962ec.appspot.com',
    measurementId: 'G-0QHXG4F41V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOw1WEOnyUO30UPu5GsOawKV6UYJUCH94',
    appId: '1:775834354005:android:8567b6729bc423983e2fdc',
    messagingSenderId: '775834354005',
    projectId: 'my-day-962ec',
    storageBucket: 'my-day-962ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3IOdZoK8aa6gOcM-lyDcx3oFnPXzwvC0',
    appId: '1:775834354005:ios:99f02fc28d06963d3e2fdc',
    messagingSenderId: '775834354005',
    projectId: 'my-day-962ec',
    storageBucket: 'my-day-962ec.appspot.com',
    iosBundleId: 'com.example.myDay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3IOdZoK8aa6gOcM-lyDcx3oFnPXzwvC0',
    appId: '1:775834354005:ios:99f02fc28d06963d3e2fdc',
    messagingSenderId: '775834354005',
    projectId: 'my-day-962ec',
    storageBucket: 'my-day-962ec.appspot.com',
    iosBundleId: 'com.example.myDay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPD5Zma9lMNjonB__6BBTNOdc5O7Qf5zU',
    appId: '1:775834354005:web:af4e311d16445db83e2fdc',
    messagingSenderId: '775834354005',
    projectId: 'my-day-962ec',
    authDomain: 'my-day-962ec.firebaseapp.com',
    storageBucket: 'my-day-962ec.appspot.com',
    measurementId: 'G-8ECNCMC2FR',
  );
}
